# Site settings
# ...
github_username:  tres-caras
nav:
  - title: "Inicio"
    url: "/"
  - title: "Acerca de Idear.io"
    url: "/acerca-de-ideario"
  - title: "Categorías"
    url: "/categorias"
  - title: "Eventos y colaboraciones"
    url: "/eventos-y-colaboraciones"
  - title: "Comunidad"
    url: "/comunidad"
  - title: "Testimonios y casos de éxito"
    url: "/testimonios-y-casos-de-exito"
  - title: "Contacto"
    url: "/contacto"
# Build settings
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
  